//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicineProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineSupplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicineSupplier()
        {
            this.MedicinePurchases = new HashSet<MedicinePurchase>();
        }
    
        public int MedicineSupplierId { get; set; }
        public string MedicineSupplierName { get; set; }
        public Nullable<int> Mobile { get; set; }
        public string Address { get; set; }
        public string ManagerName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicinePurchase> MedicinePurchases { get; set; }
    }
}
