//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicineProjects.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;
	using System.ComponentModel.DataAnnotations;

	public partial class MedicineSale
    {
        [DisplayName("SaleId")]
        public int MedicineSaleId { get; set; }
        public Nullable<int> MedicineId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> SalePointID { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> SaleDate { get; set; }
        [DataType(DataType.Date)]
        [DisplayName("Expire")]
        public string ExpireDate { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> NetTotalPrice { get; set; }
        [DisplayName("StockStatus")]
        public string MedicineStockStatus { get; set; }
        public Nullable<int> MemoNo { get; set; }
        [DisplayName("Comment")]
        public string Comments { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Medicine Medicine { get; set; }
        public virtual TblSalePoint TblSalePoint { get; set; }
    }
}
