//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicineProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineStock
    {
        public int MedicineStockId { get; set; }
        public Nullable<int> MedicineId { get; set; }
        public Nullable<int> SalePointID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Status { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual TblSalePoint TblSalePoint { get; set; }
    }
}
