//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicineProjects.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicineSalesEntities : DbContext
    {
        public MedicineSalesEntities()
            : base("name=MedicineSalesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblSalePoint> TblSalePoints { get; set; }
        public virtual DbSet<TblUser> TblUsers { get; set; }
        public virtual DbSet<TblUserRole> TblUserRoles { get; set; }
        public virtual DbSet<MedicineSupplier> MedicineSuppliers { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Medicine> Medicines { get; set; }
        public virtual DbSet<TblMedicineCategory> TblMedicineCategories { get; set; }
        public virtual DbSet<MedicineStock> MedicineStocks { get; set; }
        public virtual DbSet<MedicinePurchase> MedicinePurchases { get; set; }
        public virtual DbSet<MedicineSale> MedicineSales { get; set; }
    }
}
